---
- name: Create ELK pod
  containers.podman.podman_pod:
    name: "{{ install_pod }}"
    hostname: "{{ install_hostname }}"
    state: started
    ports:
      - 5601:5601
      - 8085:8085
      - 9200:9200
      - 443:443

- name: Create kibana container
  containers.podman.podman_container:
    name: kibana
    state: started
    pod: "{{ install_pod }}"
    image: "docker.elastic.co/kibana/kibana:{{ install_version }}"

- name: Create logstash container
  containers.podman.podman_container:
    name: logstash
    state: started
    pod: "{{ install_pod }}"
    image: "docker.elastic.co/logstash/logstash:{{ install_version }}"
    volume:
      - /etc/logstash/pipeline:/usr/share/logstash/pipeline

- name: Create elasticsearch container
  containers.podman.podman_container:
    name: elasticsearch
    state: started
    pod: "{{ install_pod }}"
    image: "docker.elastic.co/elasticsearch/elasticsearch:{{ install_version }}"
    env:
      discovery.type: single-node
    volume:
      - /etc/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
